### PR TITLE
Wrapper SAVE logic issue

### PR DESCRIPTION
**Pull request by ChicagoDave**
New story file causes an error. It shouldn't.

### CODE REVIEW

**Comment by ChicagoDave** [comment]
D:\Dropbox\GitHub\glulx-typescript-chicagodave\glulx-typescript\example\node\engineWrapper>node engineWrapper.js ifpress.ulx test
{"MAIN":"\n\nStop the IFPress!\nAn IF Press Demonstration by David Cornelson\nRelease 1 / Serial number 160427 / Inform 7 build 6L38 (I6/v6.33 lib 6/12N) \n\nReporters and other personnel sit ensconced in small metal desks, tapping away on typewriters recently converted to manual interaction (they once acted via magical spells).\n\n","INFO":"{ storyTitle: \"Stop the IFPress!\", storyHeadline: \"An IF Press Demonstration\", storyAuthor: \"David Cornelson\", storyCreationYear: \"2016\", releaseNumber: \"1\", serialNumber: \"160427\", inform7Build: \"6L38\", inform6Library: \"6.33\", inform7Library: \"6/12N\", strictMode: \"\", debugMode: \"\" }","PLOG":"During the Great Underground Industrial Revolution, immediately following the disappearance of magic, the IF Press Gazette was created to make up for the lost tradition of the New Zork Times. Even without magic, some things seemed to get done in magical ways...\n","PRPT":">","LOCN":"The Offices","SCOR":"0","TIME":"540","TURN":"1"}

D:\Dropbox\GitHub\glulx-typescript-chicagodave\glulx-typescript\example\node\engineWrapper>node engineWrapper.js ifpress.ulx test "n"
{"MAIN":"\nAmidst the cavernous warehouse are large printing presses, large rolls of paper, and barrels of ink. Men and women scurry about, putting tomorrow's edition of the IF Press Gazette together. The loading dock is to the north while the offices are to the south.\n\n","PRPT":">","LOCN":"Press Room","SCOR":"0","TIME":"541","TURN":"2"}

D:\Dropbox\GitHub\glulx-typescript-chicagodave\glulx-typescript\example\node\engineWrapper>node engineWrapper.js ifpress.ulx test "n"
{"MAIN":"\nTrucks flow in and out of the docking area, picking up stacks of bound copies of the IF Press Gazette.\n\nWhat do you wish to name your World?\n\n","PRPT":">>","LOCN":"Dock","SCOR":"0","TIME":"542","TURN":"3"}
D:\Dropbox\GitHub\glulx-typescript-chicagodave\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3344
                throw new Error("Illegal state, engine did not respond to SAVE command");
                ^

Error: Illegal state, engine did not respond to SAVE command
    at EngineWrapper.saveGame (D:\Dropbox\GitHub\glulx-typescript-chicagodave\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3344:23)
    at Object.<anonymous> (D:\Dropbox\GitHub\glulx-typescript-chicagodave\glulx-typescript\example\node\engineWrapper\engineWrapper.js:3481:61)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by ChicagoDave** [comment]
Yeah it's this code:

        /**
         * convenience method to run "save"
         */
        EngineWrapper.prototype.saveGame = function () {
            var state = this.receiveLine("save");
            if (state.state !== 53 /* waitingForGameSavedConfirmation */)
                throw new Error("Illegal state, engine did not respond to SAVE command");
            var game = state.gameBeingSaved;
            this.saveGameDone(true);
            return game;
        };

As I mentioned, I don't think this code is necessary. Before the engine fires OutputReady, we should take a Quetzal snapshot internally and expose it publicly.

Then instead of running an actual game 'save' command, we can just grab engine.saveData.

The design in the story is not exactly "standard", but it's not uncommon, so we have manage it somehow. I'd prefer to avoid needing to call the VM for a save anyway, since on the last turn we already have everything we need.

**Comment by thiloplanz** [comment]
Well, that is exactly the issue with how the save mechanism currently works. All it does is type "save" into the command prompt (and expects the game to then generate a "saveGame" event). If the command prompt is "What do you want to name your world?" that doesn't work.

We have #16 to address that (and the workaround with the undo state that you mention may just work here, too)

**Comment by thiloplanz** [comment]
Is the ifpress.ulx contained in this PR the latest one? If not, can you attach it here? It does not seem to have the new "Name the World" function yet. One day I need to set up an environment to compile them myself...

**Comment by thiloplanz** [comment]
Another possible issue in EngineWrapper is the way it collects the channel data: It expects that there is just one OutputReady event before the ReadLine event. I suppose it is possible for the game to emit multiple OutputReady events (to build the output in stages), and those would need to be combined into one big channel data result. Do you think this could happen (and can you make a test image for it)?

**Comment by ChicagoDave** [comment]
I thought the last PR commit had both source and latest image.

**Comment by ChicagoDave** [comment]
Inform 7 is an easy install.

**Comment by thiloplanz** [comment]
> Inform 7 is an easy install.

Indeed it is :-)

I have updated engineWrapper.ts to use the undo state instead of the save command to get a snapshot of the session state. Quite the hack now, but at least it seems to get past "Name the World".

**Pull request closed without merging**
