### PR TITLE
Added dist and gulpfile.js and package.json.

### PR DESCRIPTION
**Pull request by ChicagoDave**
Added files to allow use as a dependency and to compile with 'gulp compile', which puts the required files all in dist\js.

### CODE REVIEW

**Comment by thiloplanz** [comment]
Thanks for adding this. I'll pull the gulpfile and package.json.

But should the files under `/dist` be included in the source code repository as well? They are build artifacts that get generated by running `gulp`, right?

**Comment by ChicagoDave** [comment]
True, although I might take another pass at this. As a dependency, you should only get the bits you need, not the whole repo.

**Comment by thiloplanz** [comment]
How do people do this in the Gulp world? 

In Javaland, you have a "publish" task in your build system that pushes the compiled distribution (in our case the "dist" directory and metadata JSON) to a code repository (such as Maven Central).  Code that wants to use it pulls from the code repository, not from the project source code repository.

**Comment by ChicagoDave** [comment]
I think the proper way to do this is to link in Travis CI and promote a
release. When you do that, you can run the gulp compile, run tests, then
automatically create a new github release.

I can try this on my fork, but you'd have to do it for the main repo.

**Pull request closed without merging**
